#!/bin/sh -ex

DB_NAME=drupal8
DB_USER=drupal8
DB_PASS=$(mcookie)

ADMIN_NAME=admin
ADMIN_PASS=turnkey

SRC=/usr/local/src
WEBROOT=/var/www/drupal8

PHP_V=7.3
USER=www-data

# set proxy settings
[ "$FAB_HTTP_PROXY" ] && export HTTP_PROXY=$FAB_HTTP_PROXY

# increase php cli memory limit - for composer install.
sed -i "s|^memory_limit.*|memory_limit = 768M|" /etc/php/${PHP_V}/cli/php.ini

# increase php apache memory limit
sed -i "s|^memory_limit.*|memory_limit = 64M|" /etc/php/${PHP_V}/apache2/php.ini

export HTTPS_PROXY_REQUEST_FULLURI=false # work around composer not working behind proxy
export COMPOSER_MEMORY_LIMIT=-1 # temporarily disable composer memory limits during install

# install drupal8
composer create-project drupal/recommended-project $WEBROOT --no-dev --no-interaction
chown $USER:$USER $WEBROOT

# install drupal console (seems to fail if installed after drush for some reason?!)
cd $WEBROOT
composer require drupal/console:^1.0 --prefer-dist --optimize-autoloader

# install drupal console launcher
cd / # drupal self-update fails from WEBROOT?!
wget -O /usr/local/bin/drupal -L https://drupalconsole.com/installer
chmod +x /usr/local/bin/drupal
drupal self-update

# install drush
cd $WEBROOT
composer require drush/drush

# install global drush-launcher (drush installed as drupal module via composer above)
wget -O /usr/local/bin/drush https://github.com/drush-ops/drush-launcher/releases/latest/download/drush.phar
chmod +x /usr/local/bin/drush
drush self-update

CONF=$WEBROOT/web/sites/default/settings.php
cp $WEBROOT/web/sites/default/default.settings.php $CONF

service mysql start

cd $WEBROOT

MYSQL="mysql -u root -e"
$MYSQL "CREATE DATABASE $DB_NAME CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;"
$MYSQL "CREATE USER $DB_USER@localhost IDENTIFIED BY \"$DB_PASS\";"
$MYSQL "GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, INDEX, ALTER, CREATE TEMPORARY TABLES ON \
    $DB_NAME.* TO $DB_USER@localhost IDENTIFIED BY \"$DB_PASS\";"

drush site-install standard -y \
    --account-name=$ADMIN_NAME \
    --account-pass=$ADMIN_PASS \
    --site-name="TurnKey Drupal8" \
    --db-url=mysql://$DB_USER:$DB_PASS@localhost/$DB_NAME

# download and install modules
composer require drupal/ctools
composer require drupal/field_group
composer require drupal/google_analytics
composer require drupal/honeypot
composer require drupal/imce
composer require drupal/pathauto
composer require drupal/token

drush en -y \
    ctools \
    field_group \
    google_analytics \
    honeypot \
    pathauto

drush cache-rebuild

# Create default libraries path
LIBRARIES_PATH=$WEBROOT/libraries
mkdir -p $LIBRARIES_PATH/

# Ensure 'files' dir is writeable by webserver
chown -R $USER:$USER $WEBROOT/web/sites/default/files

# configure apache
a2dissite 000-default
a2ensite drupal8
a2enmod rewrite 
 
# insert "www.example.com" as default trusted_host (inithook will adjust)
NEW_LINES="\$settings['trusted_host_patterns'] = array\(\n\t'^www\\\.example\\\.com\$',\n\t'^(\\\d{1,3})\\\.(\\\d{1,3})\\\.(\\\d{1,3})\\\.(\\\d{1,3})$',\n\);\n"
sed -i "/trusted_host_patterns/,/\*\//{n;s|^$|${NEW_LINES}|}" $CONF

# disable poor mans cron and setup drush cron
cat >> $CONF << EOF

/**
 * Disable Poor Man's Cron:
 *
 * Drupal 8 enables the built-in Poor Man's Cron by default.
 * Poor Man's Cron relies on site activity to trigger Drupal's cron,
 * and is not well suited for low activity websites.
 *
 * We will use the Linux system cron and override Poor Man's Cron
 *
 * To re-enable Poor Man's Cron:
 *    Comment out the line below, and disable the system cron
 *    in /etc/cron.hourly/drupal8
 */
\$config['automated_cron.settings']['interval'] = 0;
EOF

CRON_DRUPAL=/etc/cron.hourly/drupal8
cat >$CRON_DRUPAL<<EOF
#!/bin/bash -e
# Trigger drush cron

[ -x /usr/local/bin/drush ] || exit 0

su www-data -s /bin/bash -c "/usr/local/bin/drush --quiet cron --root=/var/www/drupal8"
EOF
chmod +x $CRON_DRUPAL

# create welcome page
MYSQL_BATCH="mysql --user=root --password=$MYSQL_PASS --batch"

WELCOME='<p>Please follow these steps to set up and start using your website:</p><ol><li><strong>Configure your website:</strong> To get started, log in as <b>admin</b> and visit the <a href=\"/admin\">administration section</a>, where you can customize and configure all aspects of your website.</li><li><strong>Start posting content:</strong> When ready, delete this welcome and <a href=\"/node/add\">create content</a> for your website.</li></ol><p>For more information, please refer to the <a href=\"https://www.turnkeylinux.org/drupal8\">TurnKey Drupal8 release notes</a>, <a href=\"/admin/help\">help section</a>, or the <a href=\"http://drupal.org/handbooks\">online Drupal handbooks</a>. You may also post at the <a href=\"http://drupal.org/forum\">Drupal forum</a>, or view the wide range of <a href=\"http://drupal.org/support\">other support options</a> available.</p>'

$MYSQL_BATCH --database=$DB_NAME --execute "INSERT INTO node (nid, vid, type, uuid, langcode) VALUES (1,1,'page','dbab9403-2ebd-4fb9-8a00-e764ce980ecd','en');"

$MYSQL_BATCH --database=$DB_NAME --execute "INSERT INTO node__body (bundle, deleted, entity_id, revision_id, langcode, delta, body_value, body_summary, body_format) VALUES ('page',0,1,1,'en',0,'$WELCOME','$WELCOME','basic_html');"

#$MYSQL_BATCH --database=$DB_NAME --execute "INSERT INTO node_access (nid, langcode, fallback, gid, realm, grant_view, grant_update, grant_delete) VALUES (0,'',1,0,'all',1,0,0);"

$MYSQL_BATCH --database=$DB_NAME --execute "INSERT INTO node_field_data (nid, vid, type, langcode, title, uid, status, created, changed, promote, sticky, revision_translation_affected, default_langcode) VALUES (1,1,'page','en','Welcome to TurnKey Drupal',1,1,1435831165,1435831165,1,0,1,1);"

$MYSQL_BATCH --database=$DB_NAME --execute "INSERT INTO node_field_revision (nid, vid, langcode, title, uid, status, created, changed, promote, sticky, revision_translation_affected, default_langcode) VALUES (1,1,'en','Welcome to TurnKey Drupal',1,1,1435831165,1435831165,1,0,1,1);"

$MYSQL_BATCH --database=$DB_NAME --execute "INSERT INTO node_revision (nid, vid, langcode, revision_timestamp, revision_uid, revision_log) VALUES (1,1,'en',1435831535,1,'');"

$MYSQL_BATCH --database=$DB_NAME --execute "INSERT INTO node_revision__body (bundle, deleted, entity_id, revision_id, langcode, delta, body_value, body_summary, body_format) VALUES ('page',0,1,1,'en',0,'$WELCOME','$WELCOME','basic_html');"

# disable footer _ this is no longer the way to do it for Drupal8 but not 100% sure how to easily do it so have jsut left it as default
#$MYSQL_BATCH --database=$DB_NAME --execute "UPDATE block SET region = '-1' WHERE delta = 'powered-by';

service mysql stop

# unset proxy settings
unset HTTP_PROXY
