#!/bin/sh -ex

DB_NAME=drupal8
DB_USER=drupal8
DB_PASS=$(mcookie)

ADMIN_NAME=admin
ADMIN_PASS=turnkey

SRC=/usr/local/src
WEBROOT=/var/www/drupal8

# set proxy settings
[ "$FAB_HTTP_PROXY" ] && export HTTP_PROXY=$FAB_HTTP_PROXY

# increase php cli memory limit (for drush)
sed -i "s|^memory_limit.*|memory_limit = 128M|" /etc/php5/cli/php.ini

# increase php apache memory limit
sed -i "s|^memory_limit.*|memory_limit = 64M|" /etc/php5/apache2/php.ini

# install composer globally
curl -sS https://getcomposer.org/installer | php
mv composer.phar /usr/local/bin/composer

# install drush dev-master (drush8 required for drupal8)
git clone --depth 1 https://github.com/drush-ops/drush.git $SRC/drush
cd $SRC/drush
composer install
ln -s $SRC/drush/drush /usr/local/bin/drush
ln -s $SRC/drush/drush.complete.sh /etc/bash_completion.d/drush

mkdir -p /etc/drush
cat > /etc/drush/drushrc.php << EOF
<?php
// by default use the drupal root directory
\$options['r'] = '$WEBROOT';
EOF

# download latest drupal8 and install
drush dl drupal-8 --destination=$(dirname $WEBROOT)
mv $(dirname $WEBROOT)/drupal-8* $WEBROOT

SETTINGS=$WEBROOT/sites/default/settings.php
cp $WEBROOT/sites/default/default.settings.php $SETTINGS
chown www-data:www-data $SETTINGS

/etc/init.d/mysql start

cd $(dirname $SETTINGS)

drush site-install standard -y \
    --account-name=$ADMIN_NAME \
    --account-pass=$ADMIN_PASS \
    --site-name="TurnKey Drupal8" --db-su=root --db-su-pw=$MYSQL_PASS --db-url=mysql://$DB_USER:$DB_PASS@localhost/$DB_NAME

chown root:www-data $SETTINGS
chmod 640 $SETTINGS
chown -R www-data:www-data $WEBROOT/sites/default/files

# download and install modules
# - ckeditor now part of core
# - fivestart not yet avaialble for Drupal 8
# - tagadelic not (yet?) avaialble for Drupal 8
# - swapped colorbox for lightbox2 (no longer supported)
# - jquery_ui now part of core
# - email now part of core
# - context is no longer under development
# - migrate now part of core 
# - views core
# - entity in core
# - content_access not (yet?) avbaiable fro D8 
# - variable in core
# - votingapi not yet available for D8
# - i18n in core
drush dl --default-major=8 panels backup_migrate devel imce recaptcha pathauto globalredirect webform logintoboggan admin_menu colorbox google_analytics advanced_help rules token link date features ctools captcha

# perhaps this should now go in $WEBROOT/libraries?!?
LIBRARIES_PATH=$WEBROOT/sites/all/libraries
mkdir -p $LIBRARIES_PATH/getid3/
ln -s /usr/share/php-getid3 $LIBRARIES_PATH/getid3/getid3

chown -R root:root $WEBROOT/sites/all

# configure apache
a2dissite 000-default
a2ensite drupal8
a2enmod rewrite 

# from what I can gather currently the "poor man's cron" system is disabled by default in Drupal8 however I couldn't find 100% clear confirmation that that is the case (and will continue to be) so I  left this as is.
# disable poor mans cron and setup drush cron
cat >>$WEBROOT/sites/default/settings.php<< EOF

/**
 * Disable Poor Man's Cron:
 *
 * Drupal 7 enables the built-in Poor Man's Cron by default.
 * Poor Man's Cron relies on site activity to trigger Drupal's cron,
 * and is not well suited for low activity websites.
 *
 * We will use the Linux system cron and override Poor Man's Cron
 * by setting the cron_safe_threshold to 0.
 *
 * To re-enable Poor Man's Cron:
 *    Comment out (add a leading hash sign) the line below,
 *    and the system cron in /etc/cron.d/drupal7.
 */
\$conf['cron_safe_threshold'] = 0;
EOF

CRON_DRUPAL=/etc/cron.hourly/drupal7
cat >$CRON_DRUPAL<<EOF
#!/bin/bash -e
# Trigger drush cron

[ -x /usr/local/bin/drush ] || exit 0

su www-data -c "/usr/local/bin/drush --quiet cron"
EOF
chmod +x $CRON_DRUPAL

# create welcome page
MYSQL_BATCH="mysql --user=root --password=$MYSQL_PASS --batch"

WELCOME='<p>Please follow these steps to set up and start using your website:</p><ol><li><strong>Configure your website:</strong> To get started, log in as <b>admin</b> and visit the <a href=\"/admin\">administration section</a>, where you can customize and configure all aspects of your website.</li><li><strong>Start posting content:</strong> When ready, delete this welcome and <a href=\"/node/add\">create content</a> for your website.</li></ol><p>For more information, please refer to the <a href=\"http://www.turnkeylinux.org/drupal8\">TurnKey Drupal8 release notes</a>, <a href=\"/admin/help\">help section</a>, or the <a href=\"http://drupal.org/handbooks\">online Drupal handbooks</a>. You may also post at the <a href=\"http://drupal.org/forum\">Drupal forum</a>, or view the wide range of <a href=\"http://drupal.org/support\">other support options</a> available.</p>'

$MYSQL_BATCH --database=$DB_NAME --execute "INSERT INTO node (nid, vid, type, uuid, langcode) VALUES (1,1,'page','dbab9403-2ebd-4fb9-8a00-e764ce980ecd','en');"

$MYSQL_BATCH --database=$DB_NAME --execute "INSERT INTO node__body (bundle, deleted, entity_id, revision_id, langcode, delta, body_value, body_summary, body_format) VALUES ('page',0,1,1,'en',0,'$WELCOME','$WELCOME','basic_html');"

#$MYSQL_BATCH --database=$DB_NAME --execute "INSERT INTO node_access (nid, langcode, fallback, gid, realm, grant_view, grant_update, grant_delete) VALUES (0,'',1,0,'all',1,0,0);"

$MYSQL_BATCH --database=$DB_NAME --execute "INSERT INTO node_field_data (nid, vid, type, langcode, title, uid, status, created, changed, promote, sticky, revision_translation_affected, default_langcode) VALUES (1,1,'page','en','Welcome to TurnKey Drupal',1,1,1435831165,1435831165,1,0,1,1);"

$MYSQL_BATCH --database=$DB_NAME --execute "INSERT INTO node_field_revision (nid, vid, langcode, title, uid, status, created, changed, promote, sticky, revision_translation_affected, default_langcode) VALUES (1,1,'en','Welcome to TurnKey Drupal',1,1,1435831165,1435831165,1,0,1,1);"

$MYSQL_BATCH --database=$DB_NAME --execute "INSERT INTO node_revision (nid, vid, langcode, revision_timestamp, revision_uid, revision_log) VALUES (1,1,'en',1435831535,1,'');"

$MYSQL_BATCH --database=$DB_NAME --execute "INSERT INTO node_revision__body (bundle, deleted, entity_id, revision_id, langcode, delta, body_value, body_summary, body_format) VALUES ('page',0,1,1,'en',0,'$WELCOME','$WELCOME','basic_html');"

# disable footer _ this is no longer the way to do it for Drupal8 but not 100% sure how to easily do it so have jsut left it as default
#$MYSQL_BATCH --database=$DB_NAME --execute "UPDATE block SET region = '-1' WHERE delta = 'powered-by';

/etc/init.d/mysql stop

# unset proxy settings
unset HTTP_PROXY

