#!/bin/sh -ex

DB_NAME=drupal8
DB_USER=drupal8
DB_PASS=$(mcookie)

ADMIN_NAME=admin
ADMIN_PASS=turnkey

SRC=/usr/local/src
WEBROOT=/var/www/drupal8

# set proxy settings
[ "$FAB_HTTP_PROXY" ] && export HTTP_PROXY=$FAB_HTTP_PROXY

# increase php cli memory limit (for drush)
sed -i "s|^memory_limit.*|memory_limit = 128M|" /etc/php5/cli/php.ini

# increase php apache memory limit
sed -i "s|^memory_limit.*|memory_limit = 64M|" /etc/php5/apache2/php.ini

# install composer globally
curl -sS https://getcomposer.org/installer | php
mv composer.phar /usr/local/bin/composer

# install drush dev-master (drush8 required for drupal8)
git clone --branch 8.0.x --depth 1 https://github.com/drush-ops/drush.git $SRC/drush
cd $SRC/drush
composer install
ln -s $SRC/drush/drush /usr/local/bin/drush
ln -s $SRC/drush/drush.complete.sh /etc/bash_completion.d/drush

mkdir -p /etc/drush
cat > /etc/drush/drushrc.php << EOF
<?php
// by default use the drupal root directory
\$options['r'] = '$WEBROOT';
EOF

# download latest drupal8 and install
drush dl drupal-8 --destination=$(dirname $WEBROOT)
mv $(dirname $WEBROOT)/drupal-8* $WEBROOT

CONF=$WEBROOT/sites/default/settings.php
cp $WEBROOT/sites/default/default.settings.php $CONF
chown www-data:www-data $CONF

/etc/init.d/mysql start

cd $(dirname $CONF)

drush site-install standard -y \
    --account-name=$ADMIN_NAME \
    --account-pass=$ADMIN_PASS \
    --site-name="TurnKey Drupal8" --db-su=root --db-su-pw=$MYSQL_PASS --db-url=mysql://$DB_USER:$DB_PASS@localhost/$DB_NAME

chown root:www-data $CONF
chmod 640 $CONF
chown -R www-data:www-data $WEBROOT/sites/default/files

# configure apache
a2dissite 000-default
a2ensite drupal8
a2enmod rewrite 

# insert "www.example.com" as default trusted_host (inithook will adjust)
((LINE_NO=$(grep -n 'trusted_host_patterns' $CONF -A99 | grep -m 1 " \*/" | cut -d- -f1)+1))
NEW_LINES="\$settings['trusted_host_patterns'] = array\(\n\t'^www\\\.example\\\.com\$',\n\);\n"
sed -i "${LINE_NO}s|^$|${NEW_LINES}|" $CONF

# disable poor mans cron and setup drush cron
cat >> $CONF << EOF

/**
 * Disable Poor Man's Cron:
 *
 * Drupal 8 enables the built-in Poor Man's Cron by default.
 * Poor Man's Cron relies on site activity to trigger Drupal's cron,
 * and is not well suited for low activity websites.
 *
 * We will use the Linux system cron and override Poor Man's Cron
 *
 * To re-enable Poor Man's Cron:
 *    Comment out the line below, and disable the system cron
 *    in /etc/cron.hourly/drupal8
 */
\$config['automated_cron.settings']['interval'] = 0;
EOF

CRON_DRUPAL=/etc/cron.hourly/drupal8
cat >$CRON_DRUPAL<<EOF
#!/bin/bash -e
# Trigger drush cron

[ -x /usr/local/bin/drush ] || exit 0

su www-data -c "/usr/local/bin/drush cron"
EOF
chmod +x $CRON_DRUPAL

# create welcome page
MYSQL_BATCH="mysql --user=root --password=$MYSQL_PASS --batch"

WELCOME='<p>Please follow these steps to set up and start using your website:</p><ol><li><strong>Configure your website:</strong> To get started, log in as <b>admin</b> and visit the <a href=\"/admin\">administration section</a>, where you can customize and configure all aspects of your website.</li><li><strong>Start posting content:</strong> When ready, delete this welcome and <a href=\"/node/add\">create content</a> for your website.</li></ol><p>For more information, please refer to the <a href=\"https://www.turnkeylinux.org/drupal8\">TurnKey Drupal8 release notes</a>, <a href=\"/admin/help\">help section</a>, or the <a href=\"http://drupal.org/handbooks\">online Drupal handbooks</a>. You may also post at the <a href=\"http://drupal.org/forum\">Drupal forum</a>, or view the wide range of <a href=\"http://drupal.org/support\">other support options</a> available.</p>'

$MYSQL_BATCH --database=$DB_NAME --execute "INSERT INTO node (nid, vid, type, uuid, langcode) VALUES (1,1,'page','dbab9403-2ebd-4fb9-8a00-e764ce980ecd','en');"

$MYSQL_BATCH --database=$DB_NAME --execute "INSERT INTO node__body (bundle, deleted, entity_id, revision_id, langcode, delta, body_value, body_summary, body_format) VALUES ('page',0,1,1,'en',0,'$WELCOME','$WELCOME','basic_html');"

#$MYSQL_BATCH --database=$DB_NAME --execute "INSERT INTO node_access (nid, langcode, fallback, gid, realm, grant_view, grant_update, grant_delete) VALUES (0,'',1,0,'all',1,0,0);"

$MYSQL_BATCH --database=$DB_NAME --execute "INSERT INTO node_field_data (nid, vid, type, langcode, title, uid, status, created, changed, promote, sticky, revision_translation_affected, default_langcode) VALUES (1,1,'page','en','Welcome to TurnKey Drupal',1,1,1435831165,1435831165,1,0,1,1);"

$MYSQL_BATCH --database=$DB_NAME --execute "INSERT INTO node_field_revision (nid, vid, langcode, title, uid, status, created, changed, promote, sticky, revision_translation_affected, default_langcode) VALUES (1,1,'en','Welcome to TurnKey Drupal',1,1,1435831165,1435831165,1,0,1,1);"

$MYSQL_BATCH --database=$DB_NAME --execute "INSERT INTO node_revision (nid, vid, langcode, revision_timestamp, revision_uid, revision_log) VALUES (1,1,'en',1435831535,1,'');"

$MYSQL_BATCH --database=$DB_NAME --execute "INSERT INTO node_revision__body (bundle, deleted, entity_id, revision_id, langcode, delta, body_value, body_summary, body_format) VALUES ('page',0,1,1,'en',0,'$WELCOME','$WELCOME','basic_html');"

# disable footer _ this is no longer the way to do it for Drupal8 but not 100% sure how to easily do it so have jsut left it as default
#$MYSQL_BATCH --database=$DB_NAME --execute "UPDATE block SET region = '-1' WHERE delta = 'powered-by';

/etc/init.d/mysql stop

# unset proxy settings
unset HTTP_PROXY

