#!/bin/bash -e
# regenerate drupal8 hash_salt and mysql password

. /etc/default/inithooks

CONF=/var/www/drupal8/sites/default/settings.php

SALT=$(mcookie)
sed -i "s|^\$drupal_hash_salt = .*|\$drupal_hash_salt = '$SALT';|" $CONF

PASSWORD=$(mcookie)
sed -i "s|^\( *\)'password'.*|\1'password' => '$PASSWORD',|" $CONF
$INITHOOKS_PATH/bin/mysqlconf.py --user=drupal8 --pass="$PASSWORD"

